### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by RawanAlmallki** [ARBML/tnkeeh#2] opened 2020-11-11 18:28 UTC
Hello, 
I used tankeeh library for data cleaning and I’m tried to read the csv file after that, it shows me this error: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 49: invalid continuation byte

I tried to use encoding but the text and columns showed as Incomprehensible symbols. Then, I tried with txt file and I had the same issue.
Any solution? 

Thanks

**Comment by zaidalyafeai** [comment] 2020-11-12 01:30
Hi we currently only support text files. Do you get the same error when you process text files?

**Comment by RawanAlmallki** [comment] 2020-11-12 11:55
> Hi we currently only support text files. Do you get the same error when you process text files?

Yes, I used this code:
`import tnkeeh as tn
tn.clean_data(file_path = '../new1.txt', save_path = '../new_tn.txt',segment = True, remove_special_chars = True, 
remove_english = True, normalize = False, remove_diacritics = True, execluded_chars = ['!', '.', '?'], remove_tatweel = True, remove_html_elements = True, remove_links = True, remove_twitter_meta = True, remove_long_words = False, remove_repeated_chars = False,  by_chunk = False, chunk_size = 100000)`

and the parameters worked (remove english word, links..etc), but the text converted to Incomprehensible arabic letters.

**Comment by zaidalyafeai** [comment] 2020-11-12 12:00
@MagedSaeed is more familiar with encodings, can you please take a look ?

**Comment by MagedSaeed** [comment] 2020-11-13 15:15
Hey @RawanAlmallki , thanks for mentioning me @zaidalyafeai 

Rawan, can you please provide a sample of the output? Also, if possible, parts of the `.txt` file?

**Comment by RawanAlmallki** [comment] 2020-11-13 21:32
Hi @MagedSaeed ,
Yes of course, this is a screenshot for text files before & after running the code.

![Screenshot (28)](https://user-images.githubusercontent.com/61437535/99122614-be0fbf00-260f-11eb-8d7e-75d7f24a324d.png)
![Screenshot (26)](https://user-images.githubusercontent.com/61437535/99122613-bcde9200-260f-11eb-9c10-afdaae4e8545.png)

**Comment by MagedSaeed** [comment] 2020-11-14 20:08
This is wired! I will try to get some Arabic text with Unicode characters, test them on colab and give you back the results. If you can copy some content of the file and paste it here, this would be great too.

**Comment by RawanAlmallki** [comment] 2020-11-15 20:41
> This is wired! I will try to get some Arabic text with Unicode characters, test them on colab and give you back the results. If you can copy some content of the file and paste it here, this would be great too.

I'll send some content of the file to your email, If it suits you?

**Comment by MagedSaeed** [comment] 2020-11-16 14:51
Yes, please

My email is mageedsaeed1@gmail.com

**Comment by zaidalyafeai** [comment] 2020-11-19 22:50
Seems the problem is solved, closing.

**Closed as completed by zaidalyafeai** 2020-11-19 22:50 UTC
